name: Update

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Steam VR Branch'
                required: false
                default: 'beta'
                type: string      

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    process:
        permissions:
            contents: write
        uses: steamtracking/gametracking/.github/workflows/gametracking.yml@reusable-workflow
        secrets: inherit
        with:
          folder: steamvr
          branch: ${{ github.event.inputs.branch }}
